stages:
  - publish
  - deploy

variables:
  TAG_LATEST: $DOCKER_NAME/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $DOCKER_NAME/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  
  script:
    - docker build -t $TAG_COMMIT .
    - docker login -u $USERNAME_DOCKER -p $PASSOWORD_DOCKER
    - docker push $TAG_COMMIT

deploy:
  image: alpine:latest
  stage: deploy
  script:
    - chmod 600 $ID_RSA
    - apk update && apk add openssh-client
    - ssh -o StrictHostKeyChecking=no -i $ID_RSA $SERVER_USER@$SERVER_IP "docker login -u $USERNAME_DOCKER -p $PASSOWORD_DOCKER"
    - ssh -o StrictHostKeyChecking=no -i $ID_RSA $SERVER_USER@$SERVER_IP "docker pull $TAG_COMMIT"
    - ssh -o StrictHostKeyChecking=no -i $ID_RSA $SERVER_USER@$SERVER_IP "docker container rm -f my-app || true"
    - ssh -o StrictHostKeyChecking=no -i $ID_RSA $SERVER_USER@$SERVER_IP "docker run -d -p 80:80 --name my-app $TAG_COMMIT"
  environment:
    name: production
    url: http://your-address-website
  only:
    - master
